/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastrace;

import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;


/**
 *
 * @author benoit
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }
    
    static Course course;
    static DefaultListModel listModel;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupVitesseMax = new javax.swing.ButtonGroup();
        buttonGroupAcceleration = new javax.swing.ButtonGroup();
        buttonGroupPneus = new javax.swing.ButtonGroup();
        labelFastRace = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        boutonLancer = new javax.swing.JButton();
        boutonPerso = new javax.swing.JButton();
        sliderNombreVoiture = new javax.swing.JSlider();
        labelConcurrent = new javax.swing.JLabel();
        panelClassement = new javax.swing.JPanel();
        panelClassement.setVisible(false);
        progresCourse = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeClassement = new javax.swing.JList<>();
        butonRetour = new javax.swing.JButton();
        btAjoutTour = new javax.swing.JButton();
        panelPerso = new javax.swing.JPanel();
        panelPerso.setVisible(false);
        radioVitesseMax1 = new javax.swing.JRadioButton();
        radioVitesseMax2 = new javax.swing.JRadioButton();
        radioVitesseMax3 = new javax.swing.JRadioButton();
        radioAcceleration1 = new javax.swing.JRadioButton();
        radioAcceleration2 = new javax.swing.JRadioButton();
        radioAcceleration3 = new javax.swing.JRadioButton();
        radioPneu1 = new javax.swing.JRadioButton();
        radioPneu2 = new javax.swing.JRadioButton();
        boutonValiderPerso = new javax.swing.JButton();
        boutonQuitterPerso = new javax.swing.JButton();
        labelVitesseMax = new javax.swing.JLabel();
        labelAcceleration = new javax.swing.JLabel();
        labelPneus = new javax.swing.JLabel();
        textfieldNom = new javax.swing.JTextField();
        labelNomPilote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fast-race");

        boutonLancer.setText("Lancer");
        boutonLancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonLancerActionPerformed(evt);
            }
        });

        boutonPerso.setText("Personnaliser");
        boutonPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonPersoActionPerformed(evt);
            }
        });

        sliderNombreVoiture.setMinorTickSpacing(10);
        sliderNombreVoiture.setPaintTicks(true);
        sliderNombreVoiture.setSnapToTicks(true);
        sliderNombreVoiture.setValue(10);
        sliderNombreVoiture.setName(""); // NOI18N

        labelConcurrent.setText("Nombre de concurrents");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(boutonLancer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelConcurrent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sliderNombreVoiture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boutonPerso)
                .addGap(172, 172, 172))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(boutonLancer)
                .addGap(49, 49, 49)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sliderNombreVoiture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConcurrent))
                .addGap(56, 56, 56)
                .addComponent(boutonPerso)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        listeClassement.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listeClassement);

        butonRetour.setText("Retour");
        butonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonRetourActionPerformed(evt);
            }
        });

        btAjoutTour.setText("Tour suivant");
        btAjoutTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjoutTourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClassementLayout = new javax.swing.GroupLayout(panelClassement);
        panelClassement.setLayout(panelClassementLayout);
        panelClassementLayout.setHorizontalGroup(
            panelClassementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClassementLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(panelClassementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progresCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
            .addGroup(panelClassementLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(panelClassementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClassementLayout.createSequentialGroup()
                        .addComponent(progresCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClassementLayout.createSequentialGroup()
                        .addComponent(btAjoutTour)
                        .addGap(64, 64, 64)
                        .addComponent(butonRetour)
                        .addGap(102, 102, 102))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClassementLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelClassementLayout.setVerticalGroup(
            panelClassementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClassementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progresCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelClassementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonRetour)
                    .addComponent(btAjoutTour))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        buttonGroupVitesseMax.add(radioVitesseMax1);
        radioVitesseMax1.setText("Basique");
        radioVitesseMax1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVitesseMax1ActionPerformed(evt);
            }
        });

        buttonGroupVitesseMax.add(radioVitesseMax2);
        radioVitesseMax2.setText("Rapide");

        buttonGroupVitesseMax.add(radioVitesseMax3);
        radioVitesseMax3.setText("Puissante");

        buttonGroupAcceleration.add(radioAcceleration1);
        radioAcceleration1.setText("Basique");

        buttonGroupAcceleration.add(radioAcceleration2);
        radioAcceleration2.setText("Normale");

        buttonGroupAcceleration.add(radioAcceleration3);
        radioAcceleration3.setText("Puissante");

        buttonGroupPneus.add(radioPneu1);
        radioPneu1.setText("Classiques");

        buttonGroupPneus.add(radioPneu2);
        radioPneu2.setText("Pluie");

        boutonValiderPerso.setText("Valider");
        boutonValiderPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderPersoActionPerformed(evt);
            }
        });

        boutonQuitterPerso.setText("Quitter");
        boutonQuitterPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonQuitterPersoActionPerformed(evt);
            }
        });

        labelVitesseMax.setText("Vitesse Max");

        labelAcceleration.setText("Acceleration");

        labelPneus.setText("Pneus");

        labelNomPilote.setText("Nom du pilote");

        javax.swing.GroupLayout panelPersoLayout = new javax.swing.GroupLayout(panelPerso);
        panelPerso.setLayout(panelPersoLayout);
        panelPersoLayout.setHorizontalGroup(
            panelPersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersoLayout.createSequentialGroup()
                .addGroup(panelPersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(boutonQuitterPerso)
                        .addGap(102, 102, 102)
                        .addComponent(boutonValiderPerso))
                    .addGroup(panelPersoLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(panelPersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomPilote)
                            .addComponent(labelVitesseMax)))
                    .addGroup(panelPersoLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(labelPneus))
                    .addGroup(panelPersoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(textfieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPersoLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(panelPersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersoLayout.createSequentialGroup()
                                .addComponent(radioPneu1)
                                .addGap(70, 70, 70)
                                .addComponent(radioPneu2))
                            .addGroup(panelPersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelPersoLayout.createSequentialGroup()
                                    .addComponent(radioAcceleration1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(radioAcceleration2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(radioAcceleration3))
                                .addGroup(panelPersoLayout.createSequentialGroup()
                                    .addComponent(radioVitesseMax1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelPersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelAcceleration)
                                        .addGroup(panelPersoLayout.createSequentialGroup()
                                            .addComponent(radioVitesseMax2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(radioVitesseMax3))))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panelPersoLayout.setVerticalGroup(
            panelPersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersoLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(labelNomPilote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textfieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelVitesseMax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioVitesseMax1)
                    .addComponent(radioVitesseMax2)
                    .addComponent(radioVitesseMax3))
                .addGap(10, 10, 10)
                .addComponent(labelAcceleration)
                .addGap(10, 10, 10)
                .addGroup(panelPersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAcceleration1)
                    .addComponent(radioAcceleration2)
                    .addComponent(radioAcceleration3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPneus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPneu1)
                    .addComponent(radioPneu2))
                .addGap(35, 35, 35)
                .addGroup(panelPersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonValiderPerso)
                    .addComponent(boutonQuitterPerso))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(labelFastRace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(0, 529, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 95, Short.MAX_VALUE)
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 95, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelClassement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelPerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFastRace))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGap(0, 398, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelClassement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonLancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonLancerActionPerformed
        panelClassement.setVisible(true);
        panelMenu.setVisible(false);
        panelPerso.setVisible(false);
        
        
        //on récupére la liste des voitures aléatoires
        ArrayList<Voiture> listeVoiture = Voiture.genererVoitures(sliderNombreVoiture.getValue());
       
        Course course = new Course(5, listeVoiture );
        
        
        
        DefaultListModel listModel = new DefaultListModel();
        

        int tourmaxCourse = course.getNbTourMax();
        for (int i = 0; i < tourmaxCourse; i++) {
            ArrayList<Voiture> classement = course.getClassement();
            listModel.clear();
            for (int j = 0; j < classement.size(); j++){
                
                //update la liste de
                listModel.addElement(classement.get(j).getNomVoiture());
                
               

            }
            listeClassement.setModel(listModel);
            
             //Update la barre de progres de la course
            progresCourse.setValue(100/tourmaxCourse*(i+1));
            if ( i==tourmaxCourse){
                for (int z =0; z< classement.size();z++)
                {
                    if (classement.indexOf(z) <1){
                        course.addArgent(200);
                    }
                    else if(classement.indexOf(z)<3){
                        course.addArgent(150);
                    }else{
                        course.addArgent(75);
                    }

                }
            }   
        }
        course = new Course(5, listeVoiture );
        listModel = new DefaultListModel();
         btAjoutTour.setVisible(true);
        
        ArrayList<Voiture> classement = course.getClassement();
        listModel.clear();
        for (int j = 0; j < classement.size(); j++){
            //update la liste des voitures
            listModel.addElement(classement.get(j).getNomVoiture());
             listeClassement.setModel(listModel);
        }     
        
        progresCourse.setValue(1);
        progresCourse.setMaximum(course.getNbTourMax());
    }//GEN-LAST:event_boutonLancerActionPerformed

    private void boutonPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonPersoActionPerformed
                panelPerso.setVisible(true);
        panelMenu.setVisible(false);
        /*Mise à jour automatique de l'Interface de personnalisation en fonction des stats de la voiture de base*/
       
        textfieldNom.setText(course.voitureJoueur.getNomVoiture());
        
        /*Vitesse max*/
        if (course.voitureJoueur.getVitesseMax()==150){
            radioVitesseMax1.setSelected(true);
        }
        else if (course.voitureJoueur.getVitesseMax()==200){
            radioVitesseMax2.setSelected(true);
        }
        else if (course.voitureJoueur.getVitesseMax()==250){
            radioVitesseMax3.setSelected(true);
        }
        /*Acceleration*/
        if (course.voitureJoueur.getAcceleration()==50){
            radioAcceleration1.setSelected(true);
        }
        else if (course.voitureJoueur.getVitesseMax()==70){
            radioAcceleration2.setSelected(true);
        }
        else if (course.voitureJoueur.getVitesseMax()==100){
            radioAcceleration3.setSelected(true);
        }
        /*Pneus*/
        if (course.voitureJoueur.isPneuPluie()==false){
            radioPneu1.setSelected(true);
        }
        else {
            radioPneu2.setSelected(true);
        }
    }//GEN-LAST:event_boutonPersoActionPerformed

    private void butonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonRetourActionPerformed
        panelClassement.setVisible(false);
        panelMenu.setVisible(true);
        panelPerso.setVisible(false);
    }//GEN-LAST:event_butonRetourActionPerformed

    private void radioVitesseMax1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVitesseMax1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioVitesseMax1ActionPerformed

    private void boutonQuitterPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonQuitterPersoActionPerformed
        panelMenu.setVisible(true);
        panelPerso.setVisible(false);   
    }//GEN-LAST:event_boutonQuitterPersoActionPerformed

    private void boutonValiderPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderPersoActionPerformed
        //On applique les modifications a la voiture du joueur
        
        course.voitureJoueur.setNomVoiture(textfieldNom.getText().toString());
        
        //Vitesse Max :
        VitesseMaxVoiture vMax; 
        if (radioVitesseMax1.isSelected()){
            vMax=VitesseMaxVoiture.BASIQUE;
        }
        else if(radioVitesseMax2.isSelected()){
            vMax=VitesseMaxVoiture.RAPIDE;
        }
        else if (radioVitesseMax3.isSelected()){
            vMax=VitesseMaxVoiture.PUISSANTE;
        }
        
        else vMax=VitesseMaxVoiture.BASIQUE;
        
        //Acceleration :
        AccelerationVoiture acc;
        
        if (radioAcceleration1.isSelected()){
            acc=AccelerationVoiture.BASIQUE;
        }
        else if (radioAcceleration2.isSelected()){
            acc=AccelerationVoiture.NORMAL;
        }
        else if (radioAcceleration2.isSelected()){
            acc=AccelerationVoiture.PUISSANTE;
        }
        else acc=AccelerationVoiture.BASIQUE;
        
        //Pneus
        boolean pneu;
        if (radioPneu1.isSelected()){
            pneu=false;
        }
        else if (radioPneu2.isSelected()){
            pneu=true;
        }
        else pneu =false;
        course.voitureJoueur.setVitesseMax(vMax.action());
        course.voitureJoueur.setAcceleration(acc.action());
        course.voitureJoueur.setPneuPluie(pneu);
        
    }//GEN-LAST:event_boutonValiderPersoActionPerformed
    private void btAjoutTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjoutTourActionPerformed
        
        ArrayList<Voiture> classement = course.getClassement();
        if(course.hasEnded()){
            listModel.clear();

            for (int j = 0; j < classement.size(); j++){
                //update la liste des voitures
                
                listModel.addElement(classement.get(j).getNomVoiture());
                listeClassement.setModel(listModel);
            }
            progresCourse.setValue(course.getTourActuel());   
        } else {
            btAjoutTour.setVisible(false);
        }
         
    }//GEN-LAST:event_btAjoutTourActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonLancer;
    private javax.swing.JButton boutonPerso;
    private javax.swing.JButton boutonQuitterPerso;
    private javax.swing.JButton boutonValiderPerso;
    private javax.swing.JButton btAjoutTour;
    private javax.swing.JButton butonRetour;
    private javax.swing.ButtonGroup buttonGroupAcceleration;
    private javax.swing.ButtonGroup buttonGroupPneus;
    private javax.swing.ButtonGroup buttonGroupVitesseMax;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel labelAcceleration;
    private javax.swing.JLabel labelConcurrent;
    private javax.swing.JLabel labelFastRace;
    private javax.swing.JLabel labelNomPilote;
    private javax.swing.JLabel labelPneus;
    private javax.swing.JLabel labelVitesseMax;
    private javax.swing.JList<String> listeClassement;
    private javax.swing.JPanel panelClassement;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPerso;
    private javax.swing.JProgressBar progresCourse;
    private javax.swing.JRadioButton radioAcceleration1;
    private javax.swing.JRadioButton radioAcceleration2;
    private javax.swing.JRadioButton radioAcceleration3;
    private javax.swing.JRadioButton radioPneu1;
    private javax.swing.JRadioButton radioPneu2;
    private javax.swing.JRadioButton radioVitesseMax1;
    private javax.swing.JRadioButton radioVitesseMax2;
    private javax.swing.JRadioButton radioVitesseMax3;
    private javax.swing.JTextField textfieldNom;
    private javax.swing.JSlider sliderNombreVoiture;
    // End of variables declaration//GEN-END:variables
}
